DROP TABLE Session;
DROP TABLE MESURE;
DROP TABLE Capteur;
DROP TABLE Raspberry;
DROP TABLE Utilisateur;

Create Table Utilisateur (
	Identifiant VARCHAR(128) PRIMARY KEY,
	Nom VARCHAR(255),
	Prenom VARCHAR(255)
);

Create Table Raspberry (
	IdRasp INT PRIMARY KEY,
	LabelZone VARCHAR(255)
);

Create Table Capteur (
	IdCapt INT PRIMARY KEY,
	LabelCapt VARCHAR(255),
	IdRasp INT
);

Create Table Evenement(
	IdEv INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	IdUser VARCHAR(128),
	IdRasp INT,
	TypeEvenement VARCHAR(255),
	Date TIMESTAMP,
	CONSTRAINT primary_key PRIMARY KEY (id)

);

Create Table Mesure (
	Date TIMESTAMP,
	Donnee FLOAT(5),
	IdCapt INT,
	PRIMARY KEY (Date, IdCapt)
);

ALTER TABLE Evenement
	ADD CONSTRAINT FK_Evenement_IDUSER FOREIGN KEY (IdUser)
		REFERENCES UTILISATEUR(Identifiant);

ALTER TABLE Evenement
	ADD CONSTRAINT FK_Evenement_IDRASP FOREIGN KEY (IdRasp)
		REFERENCES RASPBERRY(IdRasp);

ALTER TABLE CAPTEUR
	ADD CONSTRAINT FK_CAPTEUR_IDRASP FOREIGN KEY (IdRasp)
		REFERENCES RASPBERRY(IdRasp);

ALTER TABLE MESURE
	ADD CONSTRAINT FK_MESURE_IDCAPT FOREIGN KEY (IdCapt)
REFERENCES CAPTEUR(IdCapt);